systems:
  basedir: "./logs/model_comp"
  vis_every: 2000 #300
  seed: 101111024 #20220401
  localrf2_ckpt: 'logs/miti_23_localrf_test_2/miti_23.th'

model:
  model_name: "HexPlane"
  N_voxel_init: 262144 #262144
  N_voxel_final: 8000000 #262144000 #512000000 #125000000 #27000000 #8000000
  step_ratio: 0.5 #0.5
  time_grid_init: 64 #8 #64 #12 #64 #16
  time_grid_final: 500 #500 #50 #500 #24
  upsampling_type: unaligned
  upsample_list: [2000, 4000, 7000] #[20000, 40000, 70000] #[40, 80, 140] #[4000, 8000, 14000] #[20000, 40000, 70000] #[3000, 6000, 11000] #[20000, 40000, 70000]
  update_emptymask_list: [15000, 25000, 40000] #[30000, 50000, 80000] #[50, 100, 160] #[5000, 9000, 16000] #[30000, 50000, 80000] #[4000, 7000, 12000] #[30000, 50000, 80000]
  fusion_one: "multiply"
  fusion_two: "concat"
  init_scale: 0.9
  init_shift: 0.5
  density_dim: 8
  DensityMode: "general_MLP"
  depth_loss: False
  depth_loss_weight: 0.00 #0.01 #0.001
  optical_flow_loss_weight: 0.001 #0.02
  temp_con_loss_weight: 1.0 # 1.0
  sparse_loss_weight: 0.0001 # 0.001
  smooth_loss_weight: 0.01 # 0.1
  spatial_smooth_loss_weight: 0.01 # 0.1
  temporal_smooth_loss_weight: 0.01 # 0.1
  consistency_loss_weight: 0.1 # 1.0
  slow_sf_loss_weight: 0.00 # 0.01
  rgb_loss_weight: 3.0 #3.0 DynamicNeRF #1.0 HexPlane

  # TV loss
  TV_t_s_ratio: 2.0  # ratio of TV loss along temporal and spatial dimensions
  TV_weight_density: 0.0001
  TV_weight_app: 0.0001

  use_pixel_feat_sup: False
  use_pixel_feat_rgb: False
  pixel_feat_dim: 32
  pixel_feat_loss_weight: 0.1

  # last time prediction
  find_last_time: False
  time_model_ckpt: 'time_logs/miti_23-20230920-172239/miti_23.th' #'time_logs/miti_23-20230917-211908/miti_23.th' #'time_logs/miti_23-20230916-091606/miti_23.th' #'time_logs/miti_23_delta_t/miti_23.th'
  use_time_gt_volume: False
  time_gt_volume_path: 'masks/hard_t_miti_23.th'
  time_gt_volume_normals_path: 'masks/miti_23_train_occ.th'
  normals: False
  normals_path: 'masks/miti_23_train_vectors_occ.th'
  ray_reg: False
  patch_reg: False
  batch_reg: False
  img_reg: False

  # localrf
  localrf: False
  localrf_eval: False
  model_num: 0

  # Scene flow
  predict_flow: True
  use_sf_planes: False
  chain_5frames: False
  c5f_proportion: 1 #0.125 #0.125

data:
  #datadir: "/media/storage/stilz/HexPlane/data/miti_slam_nerf/23"
  datadir: "./data/miti_slam_nerf/23"
  dataset_name: "miti"
  scene_bbox_min: [-2.0, -2.0, -2.0]
  scene_bbox_max: [2.0, 2.0, 2.0]
  cal_fine_bbox: True
  downsample: 2.0
  near: 0.01
  far: 1.0
  depth_data: True
  bpixel_mask: True
  flow_data: True

  datasampler_type: "rays" #"images" #"hierach" #"rays"

optim:
  n_iters: 50000 #100000 # localHex iters per frame
  lr_decay_type: "exp"
  batch_size: 4096 #4096
  optimise_poses: False

local:
  # LocalHex
  max_drift: 1.0 #0.15
  angle_threshold: 10.0 # in degrees
  n_max_frames: 100
  progressive_opt: False
  n_init_frames: 5 #5
  use_preprocessed_poses: True
  n_overlap: 30 #30
  add_frames_every: 100

render_test: True
render_path: True
render_train: False

render_extra: False
original_pose: True # keep pose from specific scene for all timesteps
num_scene: 0
render_extra_repeats: 0 #14
img_limit: 3000 #30
eval_every_img: 10

create_pc: False
pc_test_idx: [0, 20, 40, 60, 80, 100, 120]
pc_icp: False
visualize_4d_vol: False
vis_occupancy: False

test_weights: False
test_view: 70
ray_idxs: [5000, 10000, 20000, 44000, 50000, 75000, 90000, 120000, 122000]

# LocalHex
local_models: False
debug_mode: False

expname: miti_23_tmp_opt